---
- hosts: localhost
  become: true
  vars:
    - apt_file: /etc/apt/sources.list.d/google-chrome.list
    - user_name: ja223n
  tasks:
    - name: '[DEBUG] Get HostName'
      shell: hostname
      register: r_hostname
    - name: '[DEBUG] HostName'
      debug: { var: r_hostname.stdout }
    - name: '[DEBUG] Ansible Connection'
      debug: { var: ansible_connection }
    - name: '[DEBUG] Ansible Python Interpreter'
      debug: { var: ansible_python_interpreter }
    - name: '[Chrome] Google apt file exist?'
      command: test -f {{ apt_file }}
      register: google_apt_exists
      ignore_errors: true
    - name: '[Chrome] Add Google Chrome key'
      shell: wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
      when: google_apt_exists.rc == 1
    - name: '[Chrome] Add Google Chrome repo'
      ansible.builtin.copy:
        src: google-chrome.list
        dest: /etc/apt/sources.list.d/
        owner: root
        group: root
        mode: 644
      when: google_apt_exists.rc == 1
    - name: '[Chrome] Update all packages to their latest version.'
      ansible.builtin.apt:
        name: "*"
        state: latest
    - name: '[Chrome] Upgrade the OS'
      ansible.builtin.apt:
        upgrade: dist
    - name: '[Chrome] Update apt cache'
      ansible.builtin.apt:
        update_cache: yes
    - name: '[Chrome] Install Google Chrome'
      ansible.builtin.apt:
        pkg: google-chrome-stable
        state: present
    - name: '[Vagrant] Install Vagrant.'
      ansible.builtin.apt:
        pkg: vagrant-libvirt
        state: latest
    - name: '[Vagrant] Install Daemon.'
      ansible.builtin.apt:
        pkg: libvirt-daemon-system
        state: latest
    - name: '[Vagrant] Add User Group.'
      ansible.builtin.user:
        name: "{{ user_name }}"
        group: "{{ user_name }}"
        groups: "libvirt"
        append: true
