---
# code: language=ansible
- hosts: localhost
  become: true
  pre_tasks:
    - name: "[APT] Update Package Cache"
      ansible.builtin.apt:
        update_cache: true
  roles:
    - role: chrome
      tags: role_chrome
    - role: git
      tags: role_git
    - role: vagrant
      tags: role_vagrant
  tasks:
    - name: ssh folder exists
      stat:
        path: "~ja223n/.ssh"
      register: ssh_result
      become: false
    - name: create ssh folder
      file:
        path: "~ja223n/.ssh"
        state: directory
        owner: "ja223n"
        group: "ja223n"
        mode: "700"
      when: not ssh_result.stat.exists
