---
# code: language=ansible
- hosts: localhost
  become: true
  gather_facts: yes
  pre_tasks:
    - name: "[APT] Update Package Cache"
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
    - name: "[APT] Install GDebi"
      ansible.builtin.apt:
        name: gdebi
    - name: "[APT] Install python3-venv"
      ansible.builtin.apt:
        name: python3-venv
    - name: "[APT] Install python3-pip"
      ansible.builtin.apt:
        name: python3-pip
    - name: "[APT] Install pipx"
      ansible.builtin.apt:
        name: pipx
    - name: "[APT] Install python-is-python3"
      ansible.builtin.apt:
        name: python-is-python3
    - name: '[APT] Install tree'
      ansible.builtin.apt:
        name: tree
    - name: '[APT] Install xdg-user-dirs-gtk'
      ansible.builtin.apt:
        name: xdg-user-dirs-gtk
  roles:
    - role: chrome
      tags: role_chrome
    - role: git
      tags: role_git
    - role: vagrant
      tags: role_vagrant
    - role: dell
      tags: role_dell
  tasks:
    - name: ssh folder exists
      stat:
        path: "~ja223n/.ssh"
      register: ssh_result
      become: false
    - name: create ssh folder
      file:
        path: "~ja223n/.ssh"
        state: directory
        owner: "ja223n"
        group: "ja223n"
        mode: "700"
      when: not ssh_result.stat.exists
