---
- name: '[Git-Config] Add E-Mail'
  git_config:
    name: user.email
    scope: global
    value: "{{ mail_address }}"
  become: false
- name: '[Git-Config] User Name'
  git_config:
    name: user.name
    scope: global
    value: "{{ user_name }}"
  become: false
- name: '[Git-Config] Color UI'
  git_config:
    name: color.ui
    value: "{{ color_ui }}"
  become: false
