---
- name: '[Vagrant] Install Vagrant.'
  ansible.builtin.apt:
    pkg: vagrant-libvirt
    state: latest
  become: true
- name: '[Vagrant] Install Daemon.'
  ansible.builtin.apt:
    pkg: libvirt-daemon-system
    state: latest
  become: true
- name: '[Vagrant] Add User Group.'
  ansible.builtin.user:
    name: "{{ user_name }}"
    group: "{{ user_name }}"
    groups: "libvirt"
    append: true
  become: true
