---
- name: '[Chrome] Install ca-certificates'
  ansible.builtin.apt:
    pkg: ca-certificates
  become: true
- name: '[Chrome] Install apt-transport-https'
  ansible.builtin.apt:
    pkg: apt-transport-https
  become: true
- name: '[Chrome] Get key'
  ansible.builtin.get_url:
    url: 'https://dl-ssl.google.com/linux/linux_signing_key.pub'
    dest: '/usr/share/keyrings/google.pub'
    mode: 'u=rw,go=r'
    force: true
  become: true
- name: '[Chrome] Add VSCode repo'
  ansible.builtin.apt_repository:
    repo: 'deb [arch=amd64 trusted=true signed-by=/usr/share/keyrings/google.pub] https://dl.google.com/linux/chrome/deb/ stable main'
    filename: 'chrome'
  become: true
- name: '[Chrome] Install VSCode'
  ansible.builtin.apt:
    pkg: 'google-chrome-stable'
  become: true
