---
- name: '[Chrome] Google apt file exist?'
  stat:
    path: '{{ apt_file }}'
  register: google_apt_exists
  become: true
- name: '[Chrome] Add Google Chrome key'
  shell: wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
  when: not google_apt_exists.stat.exists
  become: true
- name: '[Chrome] Add Google Chrome repo'
  ansible.builtin.copy:
    src: google-chrome.list
    dest: /etc/apt/sources.list.d/
    owner: root
    group: root
    mode: 644
  when: not google_apt_exists.stat.exists
  become: true
- name: '[Chrome] Update all packages to their latest version.'
  ansible.builtin.apt:
    name: "*"
    state: latest
  become: true
- name: '[Chrome] Update apt cache.'
  ansible.builtin.apt:
    update_cache: yes
  become: true
- name: '[Chrome] Install Google Chrome.'
  ansible.builtin.apt:
    pkg: google-chrome-stable
    state: present
  become: true
